export default [
  {
    owner: 'Earth',
    name: 'Moon',
    radius: 0.8,
    orbRadius: 384400,
    orbTime: 236059,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#bdb8b8',
    fourth: 1,
    positionX: 18,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Mars',
    name: 'Phobos',
    radius: 0.04,
    orbRadius: 6006,
    orbTime: 8640,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#7f553b',
    fourth: 1,
    positionX: 5.5,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Mars',
    name: 'Deimos',
    radius: 0.84,
    orbRadius: 23500,
    orbTime: 10907,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#a38a76',
    fourth: 1,
    positionX: 8.4,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Jupiter',
    name: 'Europe',
    radius: 0.76,
    orbRadius: 670900,
    orbTime: 30680,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.2,
    metalness: 0,
    color: '#f3e7de',
    fourth: 1,
    positionX: 80,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Jupiter',
    name: 'Ganymede',
    radius: 1.6,
    orbRadius: 1341000,
    orbTime: 61815,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#eed2bf',
    fourth: 1,
    positionX: 220,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Jupiter',
    name: 'Io',
    radius: 0.15,
    orbRadius: 3660,
    orbTime: 15285,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#cbbf69',
    fourth: 1,
    positionX: 20,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Jupiter',
    name: 'Callisto',
    radius: 1.52,
    orbRadius: 3660,
    orbTime: 1882000,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.6,
    metalness: 0.2,
    color: '#68644a',
    fourth: 1,
    positionX: 290,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Saturn',
    name: 'Titanium',
    radius: 2.37,
    orbRadius: 1221870,
    orbTime: 137764,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#34a5a4',
    fourth: 1,
    positionX: 300,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Saturn',
    name: 'Enceladus',
    radius: 0.1,
    orbRadius: 237378,
    orbTime: 11844,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#b2d4d4',
    fourth: 1,
    positionX: 84,
    positionY: 3,
    positionZ: 0,
    orbit: 0
  },
  {
    owner: 'Neptune',
    name: 'Triton',
    radius: 0.2,
    orbRadius: -354760,
    orbTime: 50803,
    widthDivisions: 32,
    heightDivisions: 32,
    roughness: 0.8,
    metalness: 0,
    color: '#ac9d89',
    fourth: 1,
    positionX: 96,
    positionY: 0,
    positionZ: 0,
    orbit: 0
  }
];
